### PR TITLE
Point back to upstream version of monoidal-containers

### PR DESCRIPTION
**Pull request by luigy**
to a version that includes a better fromList

### CODE REVIEW

**Comment by alexfmpe** [comment]
Wasn't this just removed? 
https://github.com/obsidiansystems/rhyolite/commit/7ff488b024ef5b8b72360d61aa029eb6e8aadd18#diff-5712e736e0de6ba170577f8472c398e9

**Comment by luigy** [comment]
Oh right! it would be better to revert, but at the time this got dropped it was not clear the implications of pointing back to the current hackage release version(0.4.0.0)

**Comment by ali-abrar** [comment]
What does that mean for this PR?

**Comment by luigy** [comment]
Updated this PR and went with a partial revert instead since a missing module was also added as part of the commit and updated the comment of the override

**Pull request merged**
