### PR TITLE
Remove rhyolite.request.common

### PR DESCRIPTION
**Pull request by ohri-anurag**

### CODE REVIEW

**Review by ali-abrar — CHANGES_REQUESTED** [review]
Instead of `decode` we should suggest `decodeStrictWith value'` and we should document the reason. Currently we're using `value'` which is a more lenient decoder (the less-lenient decoder only accepts arrays an objects as valid json whereas the lenient one will accept values like strings or numbers). The `'`at the end of the name is used to indicate that it is a strict (in the sense that it is not lazy) decoder.

**Comment by ali-abrar** [comment]
We should also use `decodeWith value'` or `decodeStrictWith value'` at all of the former call sites of `decodeValue'`.

**Comment by ohri-anurag** [comment]
> Instead of `decode` we should suggest `decodeStrictWith value'` and we should document the reason. Currently we're using `value'` which is a more lenient decoder (the less-lenient decoder only accepts arrays an objects as valid json whereas the lenient one will accept values like strings or numbers). The `'`at the end of the name is used to indicate that it is a strict (in the sense that it is not lazy) decoder.

image
Aeson version 0.8+ don't have any difference between json' and value', as per the documentation. I think we are already using version 1.2, since we removed the ifdefs related to aeson.

**Review by ali-abrar — APPROVED** [review]

**Comment by ali-abrar** [comment]
Thanks @ohri-anurag

**Review by ali-abrar — APPROVED** [review]

**Pull request merged**
