### PR TITLE
Add 'which' and 'staticWhich'

### PR DESCRIPTION
**Pull request by alexfmpe**

### CODE REVIEW

**Comment by 3noch** [comment]
Isn't this also defined in gargoyle? Does it make sense to pull it out into a separate package entirely?

**Comment by ryantrinkle** [comment]
It definitely makes sense to pull this into a separate package.

**Comment by alexfmpe** [comment]
`rhyolite-static.cabal` ?

**Comment by ryantrinkle** [comment]
Why not a separate package, e.g. called `which`?

**Comment by alexfmpe** [comment]
Moved to https://github.com/obsidiansystems/which

**Pull request closed without merging**
