### PR TITLE
Add journald logging datatypes on non-Linux

### PR DESCRIPTION
**Pull request by matthewbauer**
These need to be available in some cases.

### CODE REVIEW

**Comment by 3noch** [comment]
Can we just use https://github.com/obsidiansystems/rhyolite/pull/7 instead?

**Comment by 3noch** [comment]
IIRC depending on journald in cabal prevents mac support so using a cabal flag as #7 does allows you to choose this at the dependency level.

**Comment by Ericson2314** [comment]
As I commented on https://github.com/obsidiansystems/rhyolite/commit/345a0e2da57c906d93d1b10d3d8a34ff14e71d2d, I think that turning of a compiler error into a runtime error was a bad idea, and that was the domino that necessitates this. @3noch's proposal to be static and explicit (say what you mean in the CPP) is I think the right approach, and in the opposite direction.

**Comment by matthewbauer** [comment]
I don't see how introducing a cabal flag improves the situation besides making things more confusing. The issue was introduced in https://github.com/obsidiansystems/rhyolite/commit/345a0e2da57c906d93d1b10d3d8a34ff14e71d2d. I guess it's debatable whether it should be a runtime error or a type error though...

**Comment by ali-abrar** [comment]
Are users ever expected to write code that uses this constructor? If so, I'd rather not force CPP into user code, but if not we can revert https://github.com/obsidiansystems/rhyolite/commit/345a0e2da57c906d93d1b10d3d8a34ff14e71d2d and replace with another approach.

**Comment by ali-abrar** [comment]
What happened to this commit, I wonder: https://github.com/obsidiansystems/rhyolite/commit/9146836b34307498ff93e2db819b183781992958 @luigy

**Comment by 3noch** [comment]
Haha we've implemented the same thing multiple times!

**Comment by ali-abrar** [comment]
Closing in favor of #38

**Pull request closed without merging**
