### PR TITLE
Expose a function for a known set of working overrides

### PR DESCRIPTION
**Pull request by 3noch**
Pending:
  * ~https://github.com/reflex-frp/reflex/pull/226~
  * ~https://github.com/bgamari/monoidal-containers/pull/25~
  * ~https://github.com/bgamari/monoidal-containers/pull/26~

### CODE REVIEW

**Comment by 3noch** [comment]
We need more instances for `ToJSONKey`/`FromJSONKey` as reported by @luigy. However, the instances needed depend on you use case so they shouldn't necessarily block this PR. But I wouldn't be opposed to adding more now.

**Comment by luigy** [comment]
@3noch ended adding support for it here https://github.com/obsidiansystems/rhyolite/commit/b905fa34f5cdafe5f5f5eaf7e20bfff5be664297

Though I wonder if something like https://github.com/bos/aeson/issues/463 will bite us assuming it is still relevant

**Comment by 3noch** [comment]
Oh nice!

Interesting. That issue is oddly quiet...

**Comment by 3noch** [comment]
@luigy Anything else waiting for this?

**Comment by ali-abrar** [comment]
There are some conflicts. What else do we need to do to merge this?

**Comment by 3noch** [comment]
@ali-abrar I believe @matthewbauer is completely revamping this in #27.

**Comment by ali-abrar** [comment]
Alright, please close it that's the case

**Comment by 3noch** [comment]
@ali-abrar I'm not actually sure what #27 is for.

**Pull request closed without merging**
