### PR TITLE
Backend.Account: add versions of account functions that accept SecureMem

### PR DESCRIPTION
**Pull request by jmininger**
Add versions of login functions that accept SecureMem types instead of Text

### CODE REVIEW

**Comment by 3noch** [comment]
Is there any way the old functions can be written in terms of these new ones?

**Comment by xplat** [comment]
> Is there any way the old functions can be written in terms of these new ones?

there are probably ways to reduce the amount of copy-and-paste, and that should happen in a followup.

**Comment by xplat** [comment]
otherwise, lgtm

**Comment by xplat** [comment]
... except for the CI failure

**Comment by xplat** [comment]
seems the CI failure is also in the base branch, so doesn't need to be dealt with *in this PR* ...

**Pull request merged**
