### PR TITLE
Bump some deps

### PR DESCRIPTION
**Pull request by Ericson2314**
In particular go to bump-monoidal-containers-0.6, skiping the more
breaking 0.5.x. Jailbreak reflex to deal with this.

### CODE REVIEW

**Comment by ali-abrar** [comment]
Jailbreak isn't necessary: I already released 0.6.2.4 which uses
monoidal-containers 0.6.

**Comment by 3noch** [comment]
I faced that as well. I think I have a fix in my branch. I'll try to get that up.

**Comment by 3noch** [comment]
Please see #95 for my work on this.

**Comment by ali-abrar** [comment]
Closing in favor of #95

**Pull request closed without merging**
